# Generated by Django 3.2.7 on 2022-03-01 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_cc', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('gear', models.CharField(max_length=255)),
                ('drive_type', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('mpg', models.CharField(max_length=255)),
                ('market_price', models.IntegerField()),
                ('similar', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('car_trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.trim')),
            ],
        ),
    ]
